
const worldCities = [
    "New York",
    "Los Angeles",
    "London",
    "Paris",
    "Tokyo",
    "Sydney",
    "Dubai",
    "Amsterdam",
    "Moscow",
    "Berlin",
    "Rome",
    "Madrid",
    "Athens",
    "Istanbul",
    "Bangkok",
    "San Francisco",
    "Sao Paulo",
    "Mexico City",
    "Toronto",
    "Vancouver",
    "Cairo",
    "Mumbai",
    "Rio de Janeiro",
    "Seoul",
    "Shanghai",
    "Beijing",
    "Hong Kong",
    "Singapore",
    "Kuala Lumpur",
    "New Delhi",
    "Jakarta",
    "Manila",
    "Buenos Aires",
    "Santiago",
    "Lima",
    "Bogota",
    "Miami",
    "Chicago",
    "Houston",
    "Dallas",
    "Atlanta",
    "Boston",
    "Philadelphia",
    "Washington, D.C.",
    "Seattle",
    "San Diego",
    "Denver",
    "Phoenix",
    "Las Vegas",
    "San Antonio",
    "Austin",
    "Nashville",
    "New Orleans",
    "Orlando",
    "Miami Beach",
    "Fort Lauderdale",
    "Tampa",
    "Montreal",
    "Vancouver",
    "Toronto",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Quebec City",
    "Winnipeg",
    "Halifax",
    "St. John's",
    "Havana",
    "Santo Domingo",
    "San Juan",
    "Mexico City",
    "Guatemala City",
    "San Salvador",
    "Managua",
    "San Jose",
    "Panama City",
    "Belize City",
    "Caracas",
    "Bogota",
    "Quito",
    "Lima",
    "La Paz",
    "Sao Paulo",
    "Buenos Aires",
    "Santiago",
    "Montevideo",
    "Asuncion",
    "Brasilia",
    "Rio de Janeiro",
    "Cape Town",
    "Johannesburg",
    "Durban",
    "Nairobi",
    "Cairo",
    "Alexandria",
    "Casablanca",
    "Algiers",
    "Tunis",
    "Tripoli",
    "Accra",
    "Lagos",
    "Abuja",
    "N'Djamena",
    "Khartoum",
    "Addis Ababa",
    "Nairobi",
    "Kampala",
    "Dar es Salaam",
    "Lusaka",
    "Harare",
    "Pretoria",
    "Johannesburg",
    "Cape Town",
    "Kinshasa",
    "Luanda",
    "Libreville",
    "Nouakchott",
    "Dakar",
    "Banjul",
    "Conakry",
    "Freetown",
    "Monrovia",
    "Bamako",
    "Niger",
    "N'Djamena",
    "Khartoum",
    "Kampala",
    "Kigali",
    "Nairobi",
    "Maputo",
    "Lilongwe",
    "Lusaka",
    "Harare",
    "Pretoria",
    "Windhoek",
    "Gaborone",
    "Maseru",
    "Mbabane",
    "Antananarivo",
    "Nairobi",
    "Bujumbura",
    "Dodoma",
    "Kampala",
    "Juba",
    "Addis Ababa",
    "Nairobi",
    "Mogadishu",
    "Hargeisa",
    "Djibouti",
    "Asmara",
    "Khartoum",
    "Riyadh",
    "Kuwait City",
    "Manama",
    "Doha",
    "Abu Dhabi",
    "Muscat",
    "Sanaa",
    "Amman",
    "Beirut",
    "Damascus",
    "Jerusalem",
    "Baghdad",
    "Tehran",
    "Riyadh",
    "Kuwait City",
    "Manama",
    "Doha",
    "Abu Dhabi",
    "Muscat",
    "Sanaa",
    "Amman",
    "Beirut",
    "Damascus",
    "Jerusalem",
    "Baghdad",
    "Tehran",
    "Islamabad",
    "Kabul",
    "Ashgabat",
    "Tashkent",
    "Dushanbe",
    "Bishkek",
    "Astana",
    "Baku",
    "Tbilisi",
    "Yerevan",
    "Ankara",
    "Istanbul",
    "Athens",
    "Sofia",
    "Bucharest",
    "Chisinau",
    "Kiev",
    "Minsk",
    "Vilnius",
    "Riga",
    "Tallinn",
    "Helsinki",
    "Stockholm",
    "Oslo",
    "Copenhagen",
    "Reykjavik",
    "Dublin",
    "Belfast",
    "Glasgow",
    "Edinburgh",
    "Cardiff",
    "Bristol",
    "Manchester",
    "Leeds",
    "Sheffield",
    "Nottingham",
    "Newcastle",
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Brussels",
    "Antwerp",
    "Luxembourg City",
    "Paris",
    "Lyon",
    "Nice",
    "Monaco",
    "Barcelona",
    "Madrid",
    "Lisbon",
    "Rome",
    "Naples",
    "Florence",
    "Venice",
    "Milan",
    "Bologna",
    "Vienna",
    "Prague",
    "Krakow",
    "Warsaw",
    "Berlin",
    "Munich",
    "Frankfurt",
    "Zurich",
    "Geneva",
    "Barcelona",
    "Madrid",
    "Lisbon",
    "Rome",
    "Naples",
    "Florence",
    "Venice",
    "Milan",
    "Bologna",
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Brussels",
    "Antwerp",
    "Luxembourg City",
    "Paris",
    "Lyon",
    "Nice",
    "Monaco",
    "Geneva",
    "Zurich",
    "Milan",
    "Venice",
    "Rome",
    "Florence",
    "Naples",
    "Bologna",
    "Vienna",
    "Prague",
    "Krakow",
    "Warsaw",
    "Berlin",
    "Munich",
    "Frankfurt",
]

export default worldCities
